### ISSUE TITLE
error: Could not find a version that satisfies the requirement asyncserial (from miso c) (from versions: )

### ISSUE THREAD

**Issue by erickson-nist** [m-labs/pdq#12]
As I mentioned in [issue 10](https://github.com/m-labs/pdq/issues/10), I am running into issues trying to compile the gateware. I was instructed to install ISE Webpack, but I do not believe that to be the problem. I have ISE Design Suite 14.7 with the free webpack license installed. The error comes in when attempting to install misoc (migen installs just fine).

I ran the following commands:
conda update conda
pip install -e git://github.com/m-labs/misoc.git#egg=misoc

That gives the following command line output:

(C:\ProgramData\Anaconda3) C:\Users\rabi\Documents\pdq-master>conda update conda

Fetching package metadata .................
Solving package specifications: .

*#* All requested packages already installed.
*#* packages in environment at C:\ProgramData\Anaconda3:
*#*
conda                     4.3.22                   py36_0    conda-forge/label/m
ain

(C:\ProgramData\Anaconda3) C:\Users\rabi\Documents\pdq-master>pip install -e git
://github.com/m-labs/misoc.git#egg=misoc
Obtaining misoc from git+git://github.com/m-labs/misoc.git#egg=misoc
  Updating c:\users\rabi\documents\pdq-master\src\misoc clone
Requirement already satisfied: pyserial in c:\programdata\anaconda3\lib\site-pac
kages (from misoc)
Collecting asyncserial (from misoc)
  Could not find a version that satisfies the requirement asyncserial (from miso
c) (from versions: )
No matching distribution found for asyncserial (from misoc)

**Comment by jordens** [comment]
That's a migen issue. Could you file it there?
Also, since you seem to want to use conda, I have added added installation instructions for conda to the README. Please try those.

**Comment by jordens** [comment]
Also, before, you never revealed what your installation problem was. In that case usually people are having problems with ISE/Vivado. That's why we pointed you there.
