### ISSUE TITLE
add more complete ARTIQ+PDQ+SPI examples

### ISSUE THREAD

**Issue by jordens** [m-labs/pdq#14]
showing the full pipeline, see also #11.

**Comment by jordens** [comment]
@yw-nist

> uploading waveform onto pdq

Will do.

> Triggering wavefrom using hardware trigger

That's old code. and not part of this work package. But will do anyway.

> Triggering waveform using spi (already there)

> The names of the methods used there (write_config, write_frame) are not intuitive. I would put in new
> method such as select_frame/trigger_frame to replace that 3 lines of code.

The names need to match the functionality. The names you propose would not. But if `set_frame` instead of `write_frame` would help you sufficiently, I'll change it.

> Triggering particular channels within or from multiple stacks of pdq boards

That's not supported. Trigger has at most board granularity, like the hardware trigger.
If you really need this (it was not quoted and not in what we discussed way back), I can give it a try. But be aware that the design is already using 4,654 out of 4,656 slices (99.96%) and barely meeting timing. Additional features will most likely break it.

> Hardware testing routine using Artiq ADC as unittest, which can later be used as the device test.

Artiq ADC? We don't have that yet. And as I said, I suspect you guys would not run a HITL CI with that where such an hardware testing routine would make send.

**Comment by dhslichter** [comment]
>But if set_frame instead of write_frame would help you sufficiently, I'll change it.

Something like `set_config_reg`, `set_checksum_reg`, `set_frame_reg` might be clearer/more unified, if slightly more verbose?  

>Artiq ADC? We don't have that yet. And as I said, I suspect you guys would not run a HITL CI with that where such an hardware testing routine would make send.

Agreed, let's not bother with this right now.  If Quantum II needs this down the line, they can do the development for it.

**Comment by jordens** [comment]
But (apart from memories) everything is just registers. Let's do `{set,get}_{checksum,frame,config}`.

**Comment by yw-nist** [comment]
> But (apart from memories) everything is just registers. Let's do {set,get}_{checksum,frame,config}.

That looks good me.
