### ISSUE TITLE
register readback?

### ISSUE THREAD

**Issue by dhslichter** [m-labs/pdq#15]
I must be missing something, but there doesn't appear to be a host command to read back the registers or the memory on the PDQ.

**Comment by jordens** [comment]
https://m-labs.hk/artiq/manual-master/core_drivers_reference.html#artiq.coredevice.pdq.PDQ.read_reg
https://m-labs.hk/artiq/manual-master/core_drivers_reference.html#artiq.coredevice.pdq.PDQ.read_mem

**Comment by dhslichter** [comment]
great, thanks!
