### ISSUE TITLE
What modifications would need to be made to allow for more than 32 frames?

### ISSUE THREAD

**Issue by erickson-nist** [m-labs/pdq#17]
We are likely to run out of memory before filling all 32 frames with transport waveforms, but our pulse shapping waveforms are much simpler/smaller. The number of frames could be more limiting than memory in that instance, so we may in the future want more frames.

My attempt to allow for more frames failed. I tried changing gateware/dac.py line 68 to self.frame=Signal(max=64) then recompiled the gateware and flashed a pdq.

@jordens do you have any intuition on what else we would need to change to make this work? My understanding is the SPI communication only sends 4 bits for the frame select, so increasing the max number of frames would require modifying it as well.

**Comment by jordens** [comment]
There is an equivalent line in comm.py that needs changing as well. And the documentation. Then you can use up to 256 frames.

**Comment by jordens** [comment]
@erickson-nist ping. can we close this?

**Comment by erickson-nist** [comment]
Sorry, yes we can.

**Comment by jordens** [comment]
no problem. thanks!
