### ISSUE TITLE
wavesynth formatting: possible to define channel by a dictionary key rather than index in the channel_data array

### ISSUE THREAD

**Issue by erickson-nist** [m-labs/pdq#19]
My understanding is that the index of channel_data corresponds to the board/chip select and channel within the board. What is the reasoning for doing it this way rather than directly providing the chip select number, for example by making channel_data a dictionary instead of an array with the chip select as the key? 

I am writing this because the system we are building uses sets of 15 single channel PDQ boards per SPI line divided into 5 sets of 1 master and 2 slaves. Each of those 5 sets has their own USB connection. The simplest way to program them is to generate the 15 board wavesynth file and send that on each of the 5 UBS connections, but this wastes time by sending much more data than is necessary for the 3 boards in each stack. 

Is there currently a way to program, for example, boards 12-14 without sending data for boards 0-11?

**Comment by jordens** [comment]
The wavesynth format should be agnostic w.r.t. to the distribution of channels among boards in a compound set of multiple busses. That's why `channel_data` is a homogeneous array.
What you want to do is exactly what the `Mediator` already does (i.e. break it down into smaller wavesynth programs).
https://github.com/m-labs/pdq/blob/master/pdq/artiq/mediator.py#L201

**Comment by erickson-nist** [comment]
I'm not sure I understand. Are you saying that the index in channel_data doesn't correspond to the board/channel? I see how the linked code breaks down a wavesynth program into smaller programs, but how do the PDQs know which channel the data goes to other than its index in channel_data? In other words, if I break down a 15 channel program into 3 channel programs and send the last one to PDQs 12-14, how do they know the data is meant for them and not PDQs 0-2 (in which case they would just ignore it)?

**Comment by jordens** [comment]
@erickson-nist Their [address switches](http://pdq.readthedocs.io/en/latest/manual.html#messages) distinguish the boards. The overall channel address is a combination of DAC index and board index. https://github.com/m-labs/pdq/blob/master/pdq/host/protocol.py#L481

**Comment by jordens** [comment]
... and several PDQ stacks (each on its own bus with board addresses starting from 0) are then [concatenated](https://github.com/m-labs/pdq/blob/master/pdq/artiq/mediator.py#L159). Or is that not what you are seeing?

**Comment by erickson-nist** [comment]
I am asking about several PDQ stacks each with their own USB connection for programming but on the same SPI bus for triggering/frame select purposes, e.g. 5 stacks with address switches set to 0-2, 3-5, 6-8, 9-11, 12-14 (not all starting from 0).

My understanding is that to program (via USB) the stack of boards 12-14, the only way to do that is to also send filler data for boards 0-11 since it appears that the index in the channel_data array in the wavesynth format corresponds to the board address. If data for only 3 channels was sent to boards 12-14, they would interpret that as intended for boards 0-2, if I understand correctly. 

Is my understanding here correct? I am trying to figure out if this is an ill-advised way to do things. If my understanding is correct, it seems like that might be the case.

**Comment by jordens** [comment]
You should make the boards on each bus start with addresses from 0. That's the assumption in the code. If you can't do that then you'll have to add filler data or change the code. For the latter, give each PDQ (bus) device [knowledge](https://github.com/m-labs/pdq/blob/master/pdq/host/protocol.py#L285) about its address index (0, 3, 6, 9, 12 in your case) and then [emit board/dac numbers accordingly](https://github.com/m-labs/pdq/blob/master/pdq/host/protocol.py#L467) when serializing the data.

**Comment by erickson-nist** [comment]
Thanks, that clears things up. The idea was to spread out the addresses for individual triggering via SPI, but it looks like trying to divide one SPI bus into multiple USB buses for programming purposes introduces additional complications to consider.

**Comment by jordens** [comment]
Ah yes. The USB and SPI addresses need to be consistent. And the bus groupings should be the same as well.
