### ISSUE TITLE
Wrong waveform data written via SPI

### ISSUE THREAD

**Issue by jonaskeller** [m-labs/pdq#22]
Working around #20 for now, I'm still having issues writing waveforms via SPI. I can send a waveform via USB and then use SPI to select frames and to trigger them. However, when I switch to the SPI version of the PDQ class and send the same binary data through its `write_mem` function, the waveform I get out is (reproducible) garbage.

Since I don't want to go through the SPI signal bit by bit, a natural next step could be to read back the waveform and compare it to what was sent. Before I re-invent the wheel: does something like that already exist, or would I have to do that manually? And do you have any other suggestions where things might be going wrong?

**Comment by jordens** [comment]
Please provide the obvious context. PDQ gateware, software versions, ARTIQ versions, description of the hardware setup, your test program. It's pointless to speculate.

**Comment by jonaskeller** [comment]
Right - sorry:

The PDQ gateware is built using the latest commit from this repository (2880b59aeafa6478b2d7f16907c620100e1d8c00).
Artiq: 3.2 aa64b8a, kc705, nist_qc2 Win7 64bit.

The setup is a single PDQ board, connected via both SPI (and USB for one of the three test cases). I observe the first channel on a scope.

The `device_db` entry is

    "pdq_spi": {
        "type": "local",
        "module": "pdq.artiq.spi",
        "class": "PDQ",
        "arguments": {"spi_device": "spi2", "chip_select": 1, "num_boards": 1}
    },

I compare the following cases for writing the waveform data, before doing the frame selection and triggering via SPI:

1. Writing the waveform data using the `program()` command of the `pdq_spi` device, after adding `self.core.break_realtime()` at the beginning of https://github.com/m-labs/pdq/blob/2880b59aeafa6478b2d7f16907c620100e1d8c00/pdq/artiq/spi.py#L88
-> waveform differs significantly from what it should be (in a reproducible way)

2. Using a copied version of `program()` (from `PDQBase` in `protocol.py`) to convert the wavesynth object to binary and manually calling `write_mem()` from a kernel loop
-> same waveform as with 1.

3. Writing the waveform via USB from outside of artiq.
-> correct waveform

In all three cases, the exact same binary data is fed to the respective `write_mem()` function.

Attached are an experiment (`pdq_spi_waveform_test.py`) and, for the case of `test3()`, the python script to write the waveform data manually (`write_test_waveform_usb.py`)

[PDQ3_SPI_tests.zip](https://github.com/m-labs/pdq/files/1678839/PDQ3_SPI_tests.zip)

**Comment by jonaskeller** [comment]
I'd appreciate if you could let me know whether this is my mistake or a bug before I spend more time on it. I'd also like to make some modifications to our hardware that rely on this working and am stuck there as long as this isn't clarified.

**Comment by jordens** [comment]
I'll look at the code tonight. But if I don't see the error right away in the code, I would have to set up the complete test system again. That would take more time.

**Comment by jonaskeller** [comment]
Thanks! I have a test setup assembled here and am happy to run tests on it if that helps. I was just hoping that this will turn out to be something obvious to you (either in the code or my usage of it), which would be much more time efficient than me digging deeper into the code.

**Comment by jordens** [comment]
Ok. I'll look at it tonght or tomorrow. If that doesn't resolve it it would be great if you could capture the spi data on a scope.

**Comment by jordens** [comment]
Your code looks fine. Could you capture CS, CLK, MOSI on a scope?
If you have time, try to read back the memory using `read_mem()` and retrieve the checksum before and after the `write_mem()` using `get_crc()`

**Comment by jonaskeller** [comment]
When using the SPI version of the `write_mem()` method, `get_crc()` returns 0, while it returns a finite number if the data has been written via the method from the USB PDQ class. In both cases, I'm using the SPI version of `get_crc()`. I haven't yet checked whether the checksum for the USB data matches what I send, but would expect so from what I see on the scope.

Here's a shortened version of the experiment above and a capture of the SPI signal it produces. The columns in `SPI.txt` are time/s, CLK, MOSI, CS.
[PDQ3_SPI_waveform_capture.zip](https://github.com/m-labs/pdq/files/1725743/PDQ3_SPI_waveform_capture.zip)

Edit: Here's the same thing with a minimal waveform:
[PDQ3_SPI_waveform_capture_simpler.zip](https://github.com/m-labs/pdq/files/1725904/PDQ3_SPI_waveform_capture_simpler.zip)

**Comment by jordens** [comment]
Ah. The `spi.write_mem()` expects the data to be a list of 16 bit integers, while the `data` you get from program are bytes. Transform it like this:

```python
...
channel_data = ch.serialize()
assert len(channel_data) % 2 == 0
channel_data = [channel_data[i] | (channel_data[i + 1] << 8) for i in range(0, len(channel_data), 2)]
data_list.append(channel_data)
...
```

**Comment by jordens** [comment]
or just ```data_list.append(np.frombuffer(ch.serialize(), dtype="<u2"))```

**Comment by jonaskeller** [comment]
I tried using the first method (the second probably needs another cast, as the kernel version of `write_mem()` complains that the `<<` operator can't deal with `np.uint16`), but still don't see reasonable waveforms.

Using this waveform

	waveform = [
		[
			{
				"trigger": True,
				"duration": 1,
				"channel_data": [
					{"bias": {"amplitude": [1]}},
				],
			}
		]
	]

I get

	data_list[0]=[32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 66, 1, 3277, 8561, 1]

which produces this SPI signal (as in the example before, there's a `set_config()` command before the actual `write_mem()`): [simple_waveform_SPI_int16.txt](https://github.com/m-labs/pdq/files/1729073/simple_waveform_SPI_int16.txt)

At first glance, the binary sequence at the end looks right - I haven't checked for an overall shift, though.

**Comment by jordens** [comment]
The SPI data looks correct. Just in case the endianess is still wrong, could you try with the other endianess (`channel_data[i + 1] | (channel_data[i] << 8)`)?

**Comment by jonaskeller** [comment]
Tried, but I'm afraid it just leads to different garbage waveforms.
Just for reference, the array in this case has the form

	data_list[0]=[8192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16896, 256, 52492, 28961, 256]

Comparing the first entry for both cases (which should be the address of the frame 0 data if I'm not mistaken) the `32` from before makes more sense to me (is it correct that this is in units of 16bit, rather than bytes?).

I've also looked at the above SPI signals more carefully and agree that they make sense: a sensible 1-byte  header, two address bytes which are all zeros, then the int16 array I input.  I haven't checked whether `[66, 1, 3277, 8561, 1]` is a reasonable frame, though. (I guess I'm stating the obvious at this point).

Maybe I should look into reading back data and comparing the correct USB data to my SPI input. Or can you think of a quicker way to get a reference from the USB code?

**Comment by jordens** [comment]
Yes. The memory is 16 bit wide.
Reading back the data would be next step.
In parallel I'll check the code of `write_mem()` again.

**Comment by jonaskeller** [comment]
Either I'm doing something wrong, or the SPI `read_mem()` method isn't doing what it's supposed to:
I've attached my experiment, where I either 
- write a minimal waveform via SPI and try to read back channel 0 (`readbacktest1()`)
- only read the channel 0 memory after I externally write the waveform via USB (`readbacktest2()`)

In both cases, I end up with an array of zeros.
[pdq_spi_waveform_readback.zip](https://github.com/m-labs/pdq/files/1745897/pdq_spi_waveform_readback.zip)

Looking at the SPI signal of `readbacktest2()`, the command on MOSI seems reasonable (`0_1111_1_00`), but MISO stays completely quiet.

Here are the traces; columns are: time/s CLK MOSI CS MISO
[readback2.txt](https://github.com/m-labs/pdq/files/1746298/readback2.txt)

**Comment by jordens** [comment]
You need to `set_config()` with `aux_miso=1`.
http://pdq.readthedocs.io/en/latest/manual.html#configuration
http://pdq.readthedocs.io/en/latest/api.html#pdq.host.protocol.PDQBase.set_config

**Comment by jonaskeller** [comment]
Oh, right - my mistake.

Unfortunately, it didn't make any difference. I have yet to see a single instance of MISO going high.

To make sure it's not a hardware fault, I've tried three different boards, as well as disconnecting MISO from the SPI buffer (i.e. having only the logic analyzer connected, in case the channel is broken and pulls it down).

**Comment by jordens** [comment]
Could you try readback of config (`get_config()`)?
And the MISO you are looking at is on the board that has the address you are writing to, and it is a "master"? Could you also quickly check that the F5/AUX works by playing a waveform that toggles AUX (using usb)?
So far I didn't find anything wrong in the SPI code while doing a port of pdq to the new SPI core in ARTIQ.

**Comment by jonaskeller** [comment]
The board is a master, and I've tried both writing to its address and to `0xf` to be safe.

With `get_config()`, I see the same behavior as for `read_mem()`: all zeros.

There is actually an instance where F5/AUX goes high: when I send `set_config(aux_miso=1)` it goes high for one clock cycle at the end, but only if at least one previous `set_config()` (with or without `aux_miso=1`) has been sent since the last hardware reset.

When I set `aux_miso=0` and write a waveform via USB, F5/AUX is permanently high. I'm currently trying to find out how to change that in the waveform. When I naively change the parameter `aux` to `0` in the appended empty lines, i.e. in

https://github.com/m-labs/pdq/blob/2880b59aeafa6478b2d7f16907c620100e1d8c00/pdq/host/protocol.py#L478

F5/AUX is permanently low.

I'm not really sure what to make of all this, but it certainly excludes a hardware fault.

**Comment by jordens** [comment]
I went ahead and set up the complete testing infrastructure again. Writing and reading config/crc/frame works just fine here. I am using kc705, sma_spi as the variant, ARTIQ 3.4, pdq 3.0-rc3, and the shipped code (https://github.com/m-labs/pdq/blob/master/examples/pdq_spi.py) Please triple check your setup.
I'll re-check memory writing and reading now.

**Comment by jordens** [comment]
memory reading and writing (https://github.com/m-labs/pdq/blob/master/examples/pdq_spi.py#L77 939aa0e) works fine as well.

**Comment by jordens** [comment]
Generating waveforms on the host and writing binary waveforms via SPI plus readback also works here. The last readback word is mangled but that won't be a problem in practice (just read one more word and truncate as shown in the example).

https://github.com/m-labs/pdq/blob/702c069c94add387a57bb67efec596ee9eddc713/examples/pdq_spi.py#L137-L167

**Comment by jonaskeller** [comment]
Your code works with my setup and also helped me find my mistake:
I didn't leave enough time after a `set_config(reset=1)` command. That's why the `set_config(aux_miso=1)` and the `write_mem()` commands didn't do what they were supposed to. My above examples can be fixed by adding a `delay(10*us)` in the right place and changing the endianness of the int16 values.

Thanks for all your help with this.
