### ISSUE TITLE
PDQ data control and readback over SPI

### ISSUE THREAD

**Issue by jordens** [m-labs/pdq#4]
- [x] Gateware support for writing spline data over SPI
- [x] ARTIQ coredevice support for ^
- [x] Gateware and ARTIQ coredevice support for readback of all state and memory
- [x] ARTIQ coredevice support for ^
- [x] Gateware and ARTIQ coredevice support for forming, tracking, verifying, and resetting a checksum of all data communications
- [x] ARTIQ coredevice support for ^

**Comment by jbqubit** [comment]
Is this funded by NIST?

---

Joe Britton
Sensors and Electron Devices
Army Research Lab
2800 Powder Mill Rd
Adelphi, MD 20783
301-394-3130
joseph.w.britton5.civ@mail.mil

**Comment by jordens** [comment]
yes
