### ISSUE TITLE
Compile Error: no Xilinx tools settings file found

### ISSUE THREAD

**Issue by Justin318** [m-labs/pdq#7]
OS: 64-bit Windows
Packages migen/misoc and the Xilinx ISE design suite 11.1 installed
----------------------------------------------------------------------
During the compile process by running 
`python make.py
`
an error 
`OSError: noXilinx tools settings file found
`
The Xilinx design tools are installed in the folder 
`C:\Xilinx\11.1\ISE`
instead of 
`C:\Xilinx\11.1\ISE_DS`
as coded in \xilinx\ise.py

And in the folder C:\Xilinx\11.1\ISE, no file with name 'settings64.bat' can be found, which is searched filename in \xilinx\common.py

**Comment by jordens** [comment]
Interesting. @enjoy-digital iirc you use windows as well. have you seen this?

**Comment by sbourdeauducq** [comment]
11.1? Is there a reason you use such an old version? IIRC the name of the settings file changed in later ISE versions.

**Comment by jordens** [comment]
You can also get webpacks for 14.7 for free.

**Comment by enjoy-digital** [comment]
@jordens: ISE 14.7 is using ISE_DS and is working fine. 
@Justin318 : You should upgrade to ISE 14.7 (that is already more than 3 years old...). 

ISE 14.7 is really the version to use for FPGA that are not supported by Vivado and I'm not sure we want to support older version of ISE in migen (that will also have others bugs...)

If you want to try with ISE 11.1, just set `source` to `False` in:
https://github.com/m-labs/migen/blob/master/migen/build/xilinx/ise.py#L146
and add ISE binaries files to your Windows path.
