### ISSUE TITLE
Is it possible for you to post the compiled gateware?

### ISSUE THREAD

**Issue by erickson-nist** [m-labs/pdq#8]
Would you be willing/able to post or send privately the compiled gateware? Doing so with every commit is likely unreasonably cumbersome, but would it be possible at least for major commits like the new "pdq3" update?

**Comment by sbourdeauducq** [comment]
We're already building bitstreams automatically for ARTIQ (http://buildbot.m-labs.hk/builders/artiq-board) so it's feasible to do it at every/for most commits, but this is not set up for PDQ (needs conda files, testing, working around conda bugs, etc.).

**Comment by sbourdeauducq** [comment]
[pdq_bin_73007e926e.zip](https://github.com/m-labs/pdq/files/1091276/pdq_bin_73007e926e.zip)

**Comment by erickson-nist** [comment]
Thanks
